# Generated by Django 3.1.6 on 2021-03-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, help_text='Path of this Category', null=True, verbose_name='Path')),
                ('name', models.CharField(blank=True, help_text='Name of parameter in the pattern of url', max_length=64, null=True, verbose_name='Name')),
                ('title', models.TextField(help_text='Title of the category', verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the category', null=True, verbose_name='Description')),
                ('language', models.CharField(default='ru', help_text='Language code', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of parameter in the pattern of url', max_length=64, null=True, verbose_name='Name')),
                ('title', models.TextField(help_text='Title of the answer', verbose_name='Title')),
                ('content', models.TextField(blank=True, help_text='Content of the answer', null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
